name: clean_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.3
  get_it: ^7.6.0
  intl: ^0.18.1
  ionicons: ^0.1.2
  retrofit: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.6
  retrofit_generator: ^4.2.0
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Light.ttf
          weight: 300
